// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513025634_add-invoice")]
    partial class addinvoice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("Domain.Models.ArchivalLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BuyerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletionTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemInfoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LotOwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ItemInfoId");

                    b.HasIndex("LotOwnerId");

                    b.ToTable("ArchivalLots");
                });

            modelBuilder.Entity("Domain.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("AmountType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrackingNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Domain.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Poster")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Domain.Models.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemInfoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LotOwnerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemInfoId");

                    b.HasIndex("LotOwnerId");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginalId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models.WalletCurrency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WalletCurrency");
                });

            modelBuilder.Entity("Domain.Models.ArchivalLot", b =>
                {
                    b.HasOne("Domain.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId");

                    b.HasOne("Domain.Models.Item", "ItemInfo")
                        .WithMany()
                        .HasForeignKey("ItemInfoId");

                    b.HasOne("Domain.Models.User", "LotOwner")
                        .WithMany()
                        .HasForeignKey("LotOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Models.Money", "BoughtFor", b1 =>
                        {
                            b1.Property<Guid>("ArchivalLotId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ArchivalLotId");

                            b1.ToTable("ArchivalLots");

                            b1.WithOwner()
                                .HasForeignKey("ArchivalLotId");
                        });

                    b.Navigation("BoughtFor");

                    b.Navigation("Buyer");

                    b.Navigation("ItemInfo");

                    b.Navigation("LotOwner");
                });

            modelBuilder.Entity("Domain.Models.Item", b =>
                {
                    b.HasOne("Domain.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Models.Lot", b =>
                {
                    b.HasOne("Domain.Models.Item", "ItemInfo")
                        .WithMany()
                        .HasForeignKey("ItemInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.User", "LotOwner")
                        .WithMany()
                        .HasForeignKey("LotOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Models.Bet", "CurrentBet", b1 =>
                        {
                            b1.Property<Guid>("LotId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("BetParticipantId")
                                .HasColumnType("TEXT");

                            b1.HasKey("LotId");

                            b1.HasIndex("BetParticipantId");

                            b1.ToTable("Lots");

                            b1.HasOne("Domain.Models.User", "BetParticipant")
                                .WithMany()
                                .HasForeignKey("BetParticipantId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("LotId");

                            b1.OwnsOne("Domain.Models.Money", "BetAmount", b2 =>
                                {
                                    b2.Property<Guid>("BetLotId")
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Type")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("BetLotId");

                                    b2.ToTable("Lots");

                                    b2.WithOwner()
                                        .HasForeignKey("BetLotId");
                                });

                            b1.Navigation("BetAmount")
                                .IsRequired();

                            b1.Navigation("BetParticipant");
                        });

                    b.OwnsOne("Domain.Models.Money", "BuyoutPrice", b1 =>
                        {
                            b1.Property<Guid>("LotId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("LotId");

                            b1.ToTable("Lots");

                            b1.WithOwner()
                                .HasForeignKey("LotId");
                        });

                    b.OwnsOne("Domain.Models.Money", "MinBetCurrency", b1 =>
                        {
                            b1.Property<Guid>("LotId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("LotId");

                            b1.ToTable("Lots");

                            b1.WithOwner()
                                .HasForeignKey("LotId");
                        });

                    b.Navigation("BuyoutPrice");

                    b.Navigation("CurrentBet");

                    b.Navigation("ItemInfo");

                    b.Navigation("LotOwner");

                    b.Navigation("MinBetCurrency")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.WalletCurrency", b =>
                {
                    b.HasOne("Domain.Models.User", null)
                        .WithMany("Currencies")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("Currencies");
                });
#pragma warning restore 612, 618
        }
    }
}
